-- =============================================================================
-- SCHEMA: account
-- PROJETO: Fiscal Fácil
-- DATA: 2026-04-08
-- DESCRIÇÃO: Schema de gestão de identidade e acesso (IAM). Contém usuários,
--            sessões, roles e permissões para autenticação e RBAC do sistema.
-- =============================================================================

CREATE SCHEMA IF NOT EXISTS account;
ALTER SCHEMA account OWNER TO dorcilio;

COMMENT ON SCHEMA account IS
    'Schema de gestão de identidade e acesso (IAM). Contém usuários, sessões, roles e permissões '
    'que sustentam o sistema de autenticação e controle de acesso por papel (RBAC) do Fiscal Fácil.';

-- -----------------------------------------------------------------------------
-- 1. FUNÇÕES
-- -----------------------------------------------------------------------------

-- Função para atualizar o vetor de busca (Full Text Search)
CREATE OR REPLACE FUNCTION account.fn_update_user_fts()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.user_fts :=
        setweight(to_tsvector('public.simple_portuguese', COALESCE(NEW.full_name, '')), 'A') ||
        setweight(to_tsvector('public.simple_portuguese', COALESCE(NEW.display_name, '')), 'B') ||
        setweight(to_tsvector('public.simple_portuguese', COALESCE(NEW.email, '')), 'C') ||
        setweight(to_tsvector('public.simple_portuguese', COALESCE(NEW.cpf, '')), 'A');
    RETURN NEW;
END;
$$;

COMMENT ON FUNCTION account.fn_update_user_fts() IS
    'Atualiza o vetor FTS de account.users. Pesos: full_name e cpf = A, display_name = B, email = C.';

-- -----------------------------------------------------------------------------
-- 2. TABELAS DE DOMÍNIO
-- -----------------------------------------------------------------------------

-- Tabela: Genders
CREATE TABLE IF NOT EXISTS account.genders (
    gender_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    gender_name character varying(30) NOT NULL,
    CONSTRAINT genders_pkey PRIMARY KEY (gender_id)
);
COMMENT ON TABLE account.genders IS 'Tabela de domínio para gêneros do usuário.';
COMMENT ON COLUMN account.genders.gender_id   IS 'Identificador numérico do gênero, gerado por identidade.';
COMMENT ON COLUMN account.genders.gender_name IS 'Rótulo do gênero exibido na interface (ex: Feminino, Masculino).';

-- Tabela: Modules (RBAC)
CREATE TABLE IF NOT EXISTS account.modules (
    module_id uuid DEFAULT gen_random_uuid() NOT NULL,
    module_name character varying(100) NOT NULL,
    module_key character varying(50) NOT NULL,
    description text,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT clock_timestamp() NOT NULL,
    updated_at timestamp with time zone DEFAULT clock_timestamp() NOT NULL,
    CONSTRAINT modules_pkey PRIMARY KEY (module_id),
    CONSTRAINT modules_key_unique UNIQUE (module_key)
);

COMMENT ON TABLE account.modules IS 'Módulos funcionais do sistema utilizados no controle de acesso por papel (RBAC).';
COMMENT ON COLUMN account.modules.module_id   IS 'Identificador único do módulo (UUID).';
COMMENT ON COLUMN account.modules.module_name IS 'Nome legível do módulo exibido na interface de administração.';
COMMENT ON COLUMN account.modules.module_key  IS 'Chave técnica única do módulo, usada no código (ex: "fiscal", "users", "establishments").';
COMMENT ON COLUMN account.modules.description IS 'Descrição opcional do propósito do módulo.';
COMMENT ON COLUMN account.modules.is_active   IS 'Indica se o módulo está ativo e disponível para atribuição a roles.';
COMMENT ON COLUMN account.modules.created_at  IS 'Timestamp de criação do registro.';
COMMENT ON COLUMN account.modules.updated_at  IS 'Timestamp da última atualização do registro.';

-- Tabela: Permissions (RBAC)
CREATE TABLE IF NOT EXISTS account.permissions (
    permission_id uuid DEFAULT gen_random_uuid() NOT NULL,
    module_id uuid NOT NULL,
    permission_name character varying(100) NOT NULL,
    permission_key character varying(100) NOT NULL,
    description text,
    created_at timestamp with time zone DEFAULT clock_timestamp() NOT NULL,
    updated_at timestamp with time zone DEFAULT clock_timestamp() NOT NULL,
    CONSTRAINT permissions_pkey PRIMARY KEY (permission_id),
    CONSTRAINT permissions_key_unique UNIQUE (permission_key),
    CONSTRAINT fk_permissions_module FOREIGN KEY (module_id)
        REFERENCES account.modules (module_id) ON DELETE CASCADE
);

COMMENT ON TABLE account.permissions IS 'Permissões granulares vinculadas a módulos, atribuídas a roles para controle de acesso (RBAC).';
COMMENT ON COLUMN account.permissions.permission_id   IS 'Identificador único da permissão (UUID).';
COMMENT ON COLUMN account.permissions.module_id       IS 'Módulo ao qual esta permissão pertence (FK para account.modules).';
COMMENT ON COLUMN account.permissions.permission_name IS 'Nome legível da permissão (ex: "Editar Cadastro de Parceiros").';
COMMENT ON COLUMN account.permissions.permission_key  IS 'Chave técnica única usada no código para checagem (ex: "establishments:update").';
COMMENT ON COLUMN account.permissions.description     IS 'Descrição opcional do que esta permissão concede ao usuário.';
COMMENT ON COLUMN account.permissions.created_at      IS 'Timestamp de criação do registro.';
COMMENT ON COLUMN account.permissions.updated_at      IS 'Timestamp da última atualização do registro.';

-- Tabela: Roles (RBAC) - ATUALIZADA (S/ Slug, C/ Account_Type e Is_Owner)
CREATE TABLE IF NOT EXISTS account.roles (
    role_id uuid DEFAULT gen_random_uuid() NOT NULL,
    role_name character varying(50) NOT NULL,
    account_type character varying(30) NOT NULL,
    is_owner boolean NOT NULL DEFAULT false,
    is_system boolean DEFAULT false NOT NULL,
    modules jsonb DEFAULT '["default"]'::jsonb,
    permissions jsonb DEFAULT '["default"]'::jsonb,
    created_at timestamp with time zone DEFAULT clock_timestamp() NOT NULL,
    updated_at timestamp with time zone DEFAULT clock_timestamp() NOT NULL,
    CONSTRAINT roles_pkey PRIMARY KEY (role_id),
    CONSTRAINT roles_account_type_is_owner_unique UNIQUE (account_type, is_owner)
);
COMMENT ON TABLE account.roles IS 'Gerenciamento de perfis de acesso segmentados por tipo de conta e hierarquia de dono.';
COMMENT ON COLUMN account.roles.role_id      IS 'Identificador único da role (UUID).';
COMMENT ON COLUMN account.roles.role_name    IS 'Nome legível da role exibido na interface (ex: "Dono Escritório", "Contador Autônomo").';
COMMENT ON COLUMN account.roles.account_type IS 'Tipo de conta ao qual a role pertence: OFFICE, ACCOUNTANT, COMPANY, INDIVIDUAL.';
COMMENT ON COLUMN account.roles.is_owner     IS 'Indica se é a role principal (dona) do tenant. Apenas uma role owner por account_type.';
COMMENT ON COLUMN account.roles.is_system    IS 'Indica se a role foi criada pelo sistema e não pode ser removida pelo usuário.';
COMMENT ON COLUMN account.roles.modules      IS 'Lista JSON dos module_key acessíveis por esta role (ex: ["users", "establishments"]).';
COMMENT ON COLUMN account.roles.permissions  IS 'Lista JSON dos permission_key concedidos por esta role (ex: ["establishments:update", "establishments:sync"]).';
COMMENT ON COLUMN account.roles.created_at   IS 'Timestamp de criação do registro.';
COMMENT ON COLUMN account.roles.updated_at   IS 'Timestamp da última atualização do registro.';

-- -----------------------------------------------------------------------------
-- 3. TABELAS
-- -----------------------------------------------------------------------------

-- Tabela: Users
CREATE TABLE IF NOT EXISTS account.users (
    email character varying(320) NOT NULL,
    email_confirmed boolean DEFAULT false,
    full_name character varying(120) NOT NULL,
    display_name character varying(60),
    gender_id integer,
    birth_date date,
    avatar text,
    cpf character varying(11),
    telefone character varying(11),
    password character varying(60) NOT NULL,
    change_password boolean DEFAULT false NOT NULL,
    accept_terms boolean DEFAULT true NOT NULL,
    root boolean DEFAULT false,
    user_fts tsvector,
    created_at timestamp with time zone DEFAULT clock_timestamp() NOT NULL,
    updated_at timestamp with time zone DEFAULT clock_timestamp() NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (email),
    CONSTRAINT users_gender_id_fkey FOREIGN KEY (gender_id) REFERENCES account.genders(gender_id)
);

COMMENT ON TABLE account.users IS 'Usuários do sistema. PK é o e-mail, que serve também como identificador de login.';
COMMENT ON COLUMN account.users.email            IS 'E-mail do usuário. PK natural e credencial de login.';
COMMENT ON COLUMN account.users.email_confirmed  IS 'Indica se o e-mail foi confirmado via link enviado ao usuário.';
COMMENT ON COLUMN account.users.full_name        IS 'Nome completo do usuário conforme cadastro.';
COMMENT ON COLUMN account.users.display_name     IS 'Nome exibido na interface, pode ser diferente do nome completo.';
COMMENT ON COLUMN account.users.gender_id        IS 'FK para account.genders. Opcional.';
COMMENT ON COLUMN account.users.birth_date       IS 'Data de nascimento do usuário.';
COMMENT ON COLUMN account.users.avatar           IS 'URL ou caminho da imagem de perfil do usuário.';
COMMENT ON COLUMN account.users.cpf              IS 'CPF do usuário, somente dígitos, sem formatação.';
COMMENT ON COLUMN account.users.telefone         IS 'Telefone de contato do usuário, somente dígitos.';
COMMENT ON COLUMN account.users.password         IS 'Hash bcrypt da senha do usuário.';
COMMENT ON COLUMN account.users.change_password  IS 'Quando true, força troca de senha no próximo login.';
COMMENT ON COLUMN account.users.accept_terms     IS 'Indica se o usuário aceitou os termos de uso.';
COMMENT ON COLUMN account.users.root             IS 'Quando true, o usuário tem acesso irrestrito ao sistema (superadmin).';
COMMENT ON COLUMN account.users.user_fts         IS 'Vetor FTS calculado sobre full_name e cpf (peso A), display_name (peso B) e email (peso C).';
COMMENT ON COLUMN account.users.created_at       IS 'Timestamp de criação do registro.';
COMMENT ON COLUMN account.users.updated_at       IS 'Timestamp da última atualização do registro.';

-- Tabela: Users Sessions (Audit & Auth)
CREATE TABLE IF NOT EXISTS account.users_sessions (
    session_id uuid DEFAULT gen_random_uuid() NOT NULL,
    email character varying(320) NOT NULL,
    refresh_token text NOT NULL,
    ip_address inet,
    country character varying(90),
    region character varying(120),
    city character varying(120),
    latitude double precision,
    longitude double precision,
    created_at timestamp with time zone DEFAULT clock_timestamp() NOT NULL,
    updated_at timestamp with time zone DEFAULT clock_timestamp() NOT NULL,
    CONSTRAINT users_sessions_pkey PRIMARY KEY (session_id),
    CONSTRAINT users_sessions_email_fkey FOREIGN KEY (email) REFERENCES account.users(email) ON DELETE CASCADE
);

COMMENT ON TABLE account.users_sessions IS 'Sessões ativas de usuários. Armazena refresh tokens e contexto geográfico de cada login.';
COMMENT ON COLUMN account.users_sessions.session_id     IS 'Identificador único da sessão (UUID).';
COMMENT ON COLUMN account.users_sessions.email          IS 'E-mail do usuário proprietário da sessão (FK para account.users).';
COMMENT ON COLUMN account.users_sessions.refresh_token  IS 'Token de renovação de autenticação. Deve ser armazenado com hash em produção.';
COMMENT ON COLUMN account.users_sessions.ip_address     IS 'Endereço IP de origem do login.';
COMMENT ON COLUMN account.users_sessions.country        IS 'País detectado pelo IP no momento do login.';
COMMENT ON COLUMN account.users_sessions.region         IS 'Estado/região detectado pelo IP no momento do login.';
COMMENT ON COLUMN account.users_sessions.city           IS 'Cidade detectada pelo IP no momento do login.';
COMMENT ON COLUMN account.users_sessions.latitude       IS 'Latitude geográfica aproximada do IP de origem.';
COMMENT ON COLUMN account.users_sessions.longitude      IS 'Longitude geográfica aproximada do IP de origem.';
COMMENT ON COLUMN account.users_sessions.created_at     IS 'Timestamp de criação da sessão (momento do login).';
COMMENT ON COLUMN account.users_sessions.updated_at     IS 'Timestamp da última renovação do token.';

-- Tabela: Users Tenants (Multi-tenancy Pivot) - ATUALIZADA
CREATE TABLE IF NOT EXISTS account.users_tenants (
    user_tenant_id uuid DEFAULT gen_random_uuid() NOT NULL,
    email character varying(320) NOT NULL,
    tenant_id uuid NOT NULL,
    role_id uuid,
    is_active boolean DEFAULT true,
    joined_at timestamp with time zone DEFAULT clock_timestamp(),
    CONSTRAINT users_tenants_pkey PRIMARY KEY (user_tenant_id),
    CONSTRAINT users_tenants_email_tenant_id_key UNIQUE (email, tenant_id),
    CONSTRAINT users_tenants_email_fkey FOREIGN KEY (email) REFERENCES account.users(email) ON DELETE CASCADE,
    CONSTRAINT users_tenants_role_id_fkey FOREIGN KEY (role_id) REFERENCES account.roles(role_id),
    CONSTRAINT users_tenants_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES partner.tenants(tenant_id) ON DELETE CASCADE
);

COMMENT ON TABLE account.users_tenants IS
    'Tabela pivot de multi-tenancy. Vincula usuários a tenants com uma role específica. '
    'Um mesmo usuário pode pertencer a múltiplos tenants com roles diferentes.';
COMMENT ON COLUMN account.users_tenants.user_tenant_id IS 'Identificador único do vínculo usuário-tenant (UUID).';
COMMENT ON COLUMN account.users_tenants.email          IS 'E-mail do usuário vinculado (FK para account.users).';
COMMENT ON COLUMN account.users_tenants.tenant_id      IS 'Tenant ao qual o usuário pertence (FK para partner.tenants).';
COMMENT ON COLUMN account.users_tenants.role_id        IS 'Role atribuída ao usuário neste tenant (FK para account.roles).';
COMMENT ON COLUMN account.users_tenants.is_active      IS 'Indica se o vínculo está ativo. Falso suspende o acesso sem remover o registro.';
COMMENT ON COLUMN account.users_tenants.joined_at      IS 'Timestamp de quando o usuário foi adicionado ao tenant.';

-- -----------------------------------------------------------------------------
-- 4. ÍNDICES E TRIGGERS
-- -----------------------------------------------------------------------------

-- Users
CREATE INDEX IF NOT EXISTS idx_users_fts ON account.users USING gin (user_fts);

-- Sessions
CREATE INDEX IF NOT EXISTS idx_sessions_email ON account.users_sessions (email);

-- Roles (Otimizados para busca JSONB)
CREATE INDEX IF NOT EXISTS idx_roles_modules ON account.roles USING gin (modules);
CREATE INDEX IF NOT EXISTS idx_roles_permissions ON account.roles USING gin (permissions);

-- Permissions
CREATE INDEX IF NOT EXISTS idx_permissions_module_id ON account.permissions (module_id);

-- Users Tenants (Otimizados para JOINs)
CREATE INDEX IF NOT EXISTS idx_users_tenants_tenant_id ON account.users_tenants (tenant_id);
CREATE INDEX IF NOT EXISTS idx_users_tenants_role_id ON account.users_tenants (role_id);

-- Triggers para FTS e Updated_at
CREATE TRIGGER tr_user_fts BEFORE INSERT OR UPDATE OF full_name, display_name, email, cpf
ON account.users FOR EACH ROW EXECUTE FUNCTION account.fn_update_user_fts();

CREATE TRIGGER tr_upd_users BEFORE UPDATE ON account.users
FOR EACH ROW EXECUTE FUNCTION public.fn_update_timestamp();

CREATE TRIGGER tr_upd_roles BEFORE UPDATE ON account.roles
FOR EACH ROW EXECUTE FUNCTION public.fn_update_timestamp();

CREATE TRIGGER tr_upd_modules BEFORE UPDATE ON account.modules
FOR EACH ROW EXECUTE FUNCTION public.fn_update_timestamp();

CREATE TRIGGER tr_upd_permissions BEFORE UPDATE ON account.permissions
FOR EACH ROW EXECUTE FUNCTION public.fn_update_timestamp();

-- -----------------------------------------------------------------------------
-- 5. SEEDS (DADOS INICIAIS)
-- -----------------------------------------------------------------------------

INSERT INTO account.genders (gender_id, gender_name) VALUES
(1, 'Feminino'), (2, 'Masculino'), (3, 'Não-binário'), (4, 'Não informar')
ON CONFLICT (gender_id) DO NOTHING;

-- Seeds de Roles usando o novo padrão account_type e is_owner
INSERT INTO account.roles (role_id, role_name, account_type, is_owner, is_system, modules) VALUES
('f52bd278-2cb1-47f8-b104-c3330d9ad196', 'Dono Escritório', 'OFFICE', true, true, '["users", "establishments"]'),
('18f86b5d-787d-4986-8e46-8e032031d903', 'Contador Autônomo', 'ACCOUNTANT', true, true, '["users", "establishments"]'),
('240ee5a3-4251-4a32-9825-f201fc27a6e8', 'Profissional Liberal', 'INDIVIDUAL', true, true, '["users"]'),
('601bcd1b-fa25-4ffd-9d21-c7704ffee7d5', 'Sócio Administrador', 'COMPANY', true, true, '["users"]')
ON CONFLICT (role_id) DO NOTHING;
